# Generated by Django 4.2.2 on 2023-06-18 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_adventure'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adventure',
            new_name='adv',
        ),
    ]
