# Generated by Django 4.2.2 on 2023-06-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='date',
            field=models.DateField(default='1998-03-21'),
            preserve_default=False,
        ),
    ]
